### ISSUE TITLE
Look 4 detailed questions in the content field.

### ISSUE THREAD

**Issue by Robin-Rhee** [SpringOx/ANLock#1]
1.What's the exact difference between ANReadWriteLock & ANRecursiveRWLock
We could c the difference in performance but what's the exact difference in usage? And what's the former cannot do but the latter can especially?

2.We can take advantage of a handful of example code 2 test if an interface which implements NSCoding protocol do satisfy the recursive lock.

```
//    NSRecursiveLock *lock = [[NSRecursiveLock alloc] init];
    ANRecursiveRWLock *lock = [[ANRecursiveRWLock alloc] init];

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{

        static void (^RecursiveMethod)(int);

        RecursiveMethod = ^(int value) {

            [lock lock];
            if (value > 0) {

                NSLog(@"value = %d", value);
                sleep(2);
                RecursiveMethod(value - 1);
            }
            [lock unlock];
        };

        RecursiveMethod(5);
    });
```

If u employ the ANRecursiveRWLock instead of NSRecursiveLock which comes from OC, u'd be aware of that it's gonna be deadlocked.
As we all no, a write operation cannot b disturbed by a read operation as the logic in the code.
But could u declare what's the meaning of recursive lock on earth?
3Q in advance~

**Comment by SpringOx** [comment]
run and test the codes, not found deadlocked:
`07:44:00.938 ANLock Demo[4582:155323] value = 5`
the second Recursive Method like to not work.
