### ISSUE TITLE
Atomic test case is wrong

### ISSUE THREAD

**Issue by dreampiggy** [SpringOx/ANLock#2]
```objectivec
@property (atomic, assign) int atomicFlag;

//Atomic Flag
timeBefore = CFAbsoluteTimeGetCurrent();
for(i=0; i<count; i++){
    self.atomicFlag = 1;
}
timeCurrent = CFAbsoluteTimeGetCurrent();
printf("Atomic Set/Get used : %f\n", timeCurrent-timeBefore);
```

For atomic test case, set the same value to `non copy property` does not trigger any lock.  It just simply return. So the lock performance for `atomic` is totally wrong. You should change the test code to this:

```objectivec
@property (atomic, assign) NSUInteger atomicFlag;

self.atomicFlag = count;
```

See objective-c runtime source code for property setter:
[objc-accessor source code](https://opensource.apple.com/source/objc4/objc4-709/runtime/objc-accessors.mm.auto.html)

**Comment by SpringOx** [comment]
Yes, you are right~ thank you for sharing.Thx!

**Comment by SpringOx** [comment]
fixed.
